#!/usr/bin/env ruby

require "bundler/setup"
require "leveret"
require "leveret/cli"

if File.exist?("./config/environment.rb")
  require File.expand_path("./config/environment.rb")
end

Leveret::CLI.new(ARGV)
